# Generated by Django 4.2.5 on 2023-09-29 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=40)),
                ('model', models.CharField(max_length=40)),
                ('msrp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('color', models.CharField(max_length=30)),
                ('notes', models.TextField(max_length=1000)),
                ('engine', models.CharField(max_length=30)),
                ('is_available', models.BooleanField(default=False)),
                ('odometer', models.IntegerField()),
                ('interior', models.CharField(max_length=40)),
                ('transmission', models.CharField(choices=[('M', 'Manual'), ('A', 'Automatic'), ('D', 'Dual')], default='A', max_length=30)),
                ('condition', models.CharField(choices=[('N', 'New'), ('U', 'Used'), ('S', 'Salvage')], default='N', max_length=30)),
                ('vehicle_type', models.CharField(choices=[('C', 'Car'), ('P', 'Pickup'), ('B', 'Boat'), ('M', 'Motorcycle')], default='C', max_length=20)),
            ],
        ),
    ]
