# Generated by Django 4.2.5 on 2023-09-29 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='year',
            field=models.IntegerField(default=2010),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='msrp',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='MSRP'),
        ),
    ]
