# Generated by Django 4.2.5 on 2023-10-02 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_vehicle_image_alter_vehicle_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='dms'),
        ),
    ]
